<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>x64</Platforms>
    <InvariantGlobalization>true</InvariantGlobalization>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DebugType>embedded</DebugType>
    <Deterministic>true</Deterministic>
    <LangVersion>preview</LangVersion>
    <AssemblyName>StellaSora</AssemblyName>
    <ProductName>Stella Sora Plugin</ProductName>
    <Product>Collapse</Product>
    <Description>This library is a plugin for adding support for the game "Stella Sora" into Collapse Launcher</Description>
    <AssemblyTitle>Stella Sora Plugin</AssemblyTitle>
    <Company>Misaka10843</Company>
    <Authors>$(Company).</Authors>
    <Copyright>Copyright 2026 $(Company)</Copyright>
    <Version>0.1.4.1</Version>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <Configurations>Debug;Release</Configurations>
    <Title>Hi3Helper.Plugin.StellaSora</Title>
    <PackageProjectUrl>https://github.com/misaka10843/Hi3Helper.Plugin.StellaSora/releases</PackageProjectUrl>
    <PackageLicenseUrl>https://github.com/misaka10843/Hi3Helper.Plugin.StellaSora/blob/main/LICENSE</PackageLicenseUrl>
    <RepositoryUrl>https://github.com/misaka10843/Hi3Helper.Plugin.StellaSora</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hi3Helper.Plugin.Core\Hi3Helper.Plugin.Core.csproj"/>
    <ProjectReference Include="..\SevenZipExtractor\SevenZipExtractor\SevenZipExtractor.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Hashing" Version="10.0.1"/>
  </ItemGroup>
</Project>
